name: Test site for publicly known js vulnerabilities

on:
  push:
    branches: [gh-pages]
      
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: "https://www.aladin.co.kr/home/welcome.aspx"